KapiBara/controller_manager:
  ros__parameters:
    update_rate: 10
    #use_sim_time: true

    motors:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    ears_controller:
      type: position_controllers/JointGroupPositionController


KapiBara/motors:
  ros__parameters:

    publish_rate: 10.0

    base_frame_id: /KapiBara/base_link

    left_wheel_names: ['/KapiBara/wheel_left1_joint']
    right_wheel_names: ['/KapiBara/wheel_right3_joint']
    wheel_separation: 0.1
    wheel_radius: 0.024

    use_stamped_vel: False

KapiBara/ears_controller:
  ros__parameters:
    joints:
      - /KapiBara/right_ear_joint
      - /KapiBara/left_ear_joint